console.log(new Date())
// console.log(new Date(year, month, day, hours, minutes, seconds, milliseconds))
// console.log(new Date())
// console.log(new Date())
console.log(new Date().toLocaleString())
console.log(new Date().toString())
console.log(Date.now())
console.log(new Date(2019, 3, 12, 4, 45, 5, 5))
let myb = new Date("November 4,2021 00:05:05")
console.log(myb.toLocaleString())
console.log(Date.now())
console.log(new Date(1623237931872))
console.log(new Date(0))
